### ISSUE TITLE
BUG: Spam clicking to place pipes causes random placement

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#2] opened 2021-11-10 18:26 UTC
I can't completely reproduce it, but it's not normal

Here's the pipe network log:

```
Changed data at (4, 5) to B
Changed data at (4, 4) to T
Joined (4, 5) and (4, 4)
Changed data at (5, 5) to R
Changed data at (4, 5) to 5
Joined (5, 5) and (4, 5)
Changed data at (6, 5) to R
Changed data at (5, 5) to 1
Joined (6, 5) and (5, 5)
Changed data at (6, 6) to B
Changed data at (6, 5) to 3
Joined (6, 6) and (6, 5)
Changed data at (7, 6) to R
Changed data at (6, 6) to 5
Joined (7, 6) and (6, 6)
Changed data at (7, 7) to B
Changed data at (7, 6) to 3
Joined (7, 7) and (7, 6)
Changed data at (7, 7) to B
Joined (22, 22) and (7, 7)
Changed data at (4, 5) to L
Changed data at (5, 5) to L
Changed data at (4, 4) to B
Changed data at (4, 3) to T
Joined (4, 4) and (4, 3)
Changed data at (3, 4) to L
Changed data at (4, 4) to 6
Joined (3, 4) and (4, 4)
Changed data at (3, 4) to L
Joined (10, 12) and (3, 4)
Changed data at (3, 4) to L
Joined (9, 13) and (3, 4)
Changed data at (2, 4) to L
Changed data at (3, 4) to 1
Joined (2, 4) and (3, 4)
Changed data at (2, 4) to L
Joined (8, 12) and (2, 4)
Changed data at (2, 4) to L
Joined (6, 13) and (2, 4)
Changed data at (2, 4) to L
Joined (7, 11) and (2, 4)
Changed data at (7, 8) to B
Changed data at (7, 7) to 2
Joined (7, 8) and (7, 7)
Changed data at (3, 2) to R
Changed data at (2, 2) to L
Joined (3, 2) and (2, 2)
Changed data at (3, 2) to R
Joined (10, 7) and (3, 2)
Changed data at (3, 2) to R
Joined (10, 7) and (3, 2)
Changed data at (3, 2) to R
Joined (9, 7) and (3, 2)
Changed data at (2, 2) to L
Joined (8, 6) and (2, 2)
Changed data at (8, 6) to B
Changed data at (8, 5) to 2
Joined (8, 6) and (8, 5)
Changed data at (2, 1) to T
Changed data at (2, 2) to 5
Joined (2, 1) and (2, 2)
Changed data at (2, 1) to T
Joined (6, 7) and (2, 1)
Changed data at (1, 3) to B
Changed data at (1, 2) to T
Joined (1, 3) and (1, 2)
Changed data at (1, 3) to B
Joined (5, 9) and (1, 3)
Changed data at (1, 3) to B
Joined (5, 11) and (1, 3)
Changed data at (1, 4) to B
Changed data at (1, 3) to 2
Joined (1, 4) and (1, 3)
Changed data at (1, 4) to B
Joined (5, 12) and (1, 4)
Changed data at (1, 4) to B
Joined (5, 13) and (1, 4)
Changed data at (2, 4) to L
Joined (7, 13) and (2, 4)
Changed data at (2, 3) to L
Changed data at (3, 3) to R
Joined (2, 3) and (3, 3)
Changed data at (2, 3) to L
Joined (7, 9) and (2, 3)
Changed data at (7, 9) to B
Changed data at (7, 8) to 2
Joined (7, 9) and (7, 8)
Changed data at (2, 3) to L
Joined (6, 9) and (2, 3)
Changed data at (2, 3) to L
Joined (9, 6) and (2, 3)
Changed data at (11, 5) to B
```

Here's a screenshot:
![bug1](https://user-images.githubusercontent.com/77758464/141171601-20ba6350-5a76-4f91-a4ff-6f8a87ec6da0.PNG)

I'll add comments with new findings as needed

**Comment by Jackal-42** [comment] 2021-11-10 18:49
I'd like some confirmation on exactly what the issue is. Are you spam clicking in exactly the same spot and it places them around you? Using a macro to click extra fast? Technically, none of the connections shown in the screenshot are illegal connections. What behavior are you expecting from the pipes?

**Comment by robtech21** [comment] 2021-11-10 19:03
> I'd like some confirmation on exactly what the issue is. Are you spam clicking in exactly the same spot and it places them around you? Using a macro to click extra fast? Technically, none of the connections shown in the screenshot are illegal connections. What behavior are you expecting from the pipes?

Usually, the pipes should connect, but spam clicking around in a certain area places pipes in other places, most notably next to other facilities. There were no auto clickers or macros involved in the recreation of the bug.

I'll try to recreate it while screen recording email it to you.

**Comment by robtech21** [comment] 2021-11-10 19:13
Follow-up video with replication of similar bug:

https://user-images.githubusercontent.com/77758464/141178147-7ab29f52-2e9f-405c-b127-b2341a1bda30.mp4

**Comment by Jackal-42** [comment] 2021-11-10 19:22
All right, I think I see what you are getting at. Problem is that when you delete the corner pipe, and place a pipe in its place, it does not reconnect to the corner as intended? If so, I think it should be a quick fix. Just keep in mind that I will prevent it from executing when given more than one option to connect to because I do not know which one the player intends. Just respond to make sure that I have interpreted the bug correctly, and if there is another connection issue I have missed.

**Comment by robtech21** [comment] 2021-11-10 19:24
> All right, I think I see what you are getting at. Problem is that when you delete the corner pipe, and place a pipe in its place, it does not reconnect to the corner as intended? If so, I think it should be a quick fix. Just keep in mind that I will prevent it from executing when given more than one option to connect to because I do not know which one the player intends. Just respond to make sure that I have interpreted the bug correctly, and if there is another connection issue I have missed.

This could possibly be it, however, it doesn't explain why it accidentally deletes a pipe elsewhere.

**Comment by Jackal-42** [comment] 2021-11-11 00:58
Oh, I think I see it now. I wish you still had the pipelog from this interaction because I never experienced this issue when randomly clicking, which makes me think possibly it is a rendering issue, or browser-specific? If you could recreate this bug with the pipe log open, I think I might be able to get somewhere but until then I haven't been able to recreate this and have no idea why the game would choose to remove two segments and then puts them back immediately. Under no circumstances would the game even check that end of the pipe, so I suspect a rendering issue. Please see if you can get a recording with the pipe log open.

**Comment by Jackal-42** [comment] 2021-11-11 01:39
Follow-up: pushed a fix for another illegal connectivity bug regarding the deletion of a segment and hanging joints when drawing over the end segment of a pipe at a 45 degree angle while moving the mouse at a speed faster than one tile per frame. Perhaps see if this fixes the issue? I doubt it, though.

**Comment by robtech21** [comment] 2021-11-11 13:37
> Follow-up: pushed a fix for another illegal connectivity bug regarding the deletion of a segment and hanging joints when drawing over the end segment of a pipe at a 45 degree angle while moving the mouse at a speed faster than one tile per frame. Perhaps see if this fixes the issue? I doubt it, though.

I'll try it out, I think it might be a fix

**Comment by Jackal-42** [comment] 2021-11-11 21:41
See issue #3

**Closed as completed by Jackal-42** 2021-11-11 21:41 UTC
